spring.application.name=SecurityApp
server.port=8085

spring.security.user.name=garima
spring.security.user.password=1234


spring.datasource.url=jdbc:postgresql://localhost:5432/springbootDB
spring.datasource.username=postgres
spring.datasource.password=garima123

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
