spring.application.name=springbootmvc
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5432/springbootDB
spring.datasource.username=postgres
spring.datasource.password=garima123

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update